# Generated by Django 5.0.4 on 2025-06-23 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateField()),
                ('image', models.ImageField(upload_to='exam_images/')),
                ('is_public', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
